language: python
python:
  - 3.6

env:
  - BACKEND: gcc
  - BACKEND: mcode

install:
  - wget https://github.com/emanuelen5/GHDL-Travis-Hello-World/releases/download/v0.1-gcc/ghdl_$BACKEND.tar.gz
  - tar -vxzf ghdl_$BACKEND.tar.gz
  - chmod +x ghdl_$BACKEND/bin/ghdl
  - export PATH=$PWD/ghdl_$BACKEND/bin:$PATH
  - pip install vunit_hdl==3.5

script:
  - pushd vunit/python
  - python test.py
