language: python
python:
  - 3.6

install:
  - pushd vunit/python
  - wget https://github.com/emanuelen5/GHDL-Travis-Hello-World/releases/download/untagged-b282d7f334e9b3d3d55b/ghdl
  - pip install vunit_hdl==3.5

script:
  - python test.py
